### ISSUE TITLE
Pakit-client cannot retrieve right SLES Version

### ISSUE THREAD

**Issue by alexandrehoarau** [CESNET/pakiti-server#139]
Hi,

Indeed pakiti-client cannot get the right SLES version.As you can see below, the version is not good. It miss the SP2 (PATCH LEVEL).

Output : /etc/SuSE-release:
```
SUSE Linux Enterprise Server 12 (x86_64)
VERSION = 12
PATCHLEVEL = 2
```

pakiti-client output :
```
system: SUSE Linux Enterprise Server 12 (x86_64)
version: 1

```
Maybe It would be possible to parse the /etc/os-release file and especially "pretty name entry" , that contains

```
NAME="SLES"
VERSION="12-SP2"
VERSION_ID="12.2"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP2"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp2"

```

Thanks for your help,
Alex

**Comment by tauceti2** [comment]
Hi Alex,

Can you test the client from https://github.com/CESNET/pakiti-client/tree/detect-sles-version ? If it will be OK, then I will merge it with master.

Cheers,

Michal P.
