### ISSUE TITLE
Enhancement request: Search by package name

### ISSUE THREAD

**Issue by bluikko** [CESNET/pakiti-server#140]
Pakiti2 has a very useful feature to search hosts by specific package name (Navigation -> Package).
It would be very useful if Pakiti3 could support this also.

The feature works as so:
- Choose a package name from the list of all packages on all servers (since Pakiti3 seems to be more modern than Pakiti2, perhaps it could be something more sophisticated than a drop-down list 10,000 items long - for example a regex search that outputs a page of matched packages: search for nothing and get all the packages known to Pakiti)
- All machines that have the chosen package installed are listed, along with the specific version of the package installed

We use this feature often. For example:
- Migration planning (say java 1.7.0 to java 1.8.0)
- Evaluating if we should update some servers after an updated package was released

I recognize the project resource limitations. We've had a Pakiti3 server in "testing" for a few years or so, so we can wait for few more years if needed. Just putting this feature request out there hoping Pakiti3 to hit feature parity some day.

**Comment by tauceti2** [comment]
Hi,

search by package name is already in Pakiti3. In top menu select Packages and then you can write the name of the package (even substring). It will show you the packages, versions and hosts which has the package installed.

Cheers,

Michal P.

**Comment by bluikko** [comment]
Sorry about that. It seems I need to update to a new version then.

**Comment by bluikko** [comment]
Updated from a 2017 version to the master and at least now I notice the "Packages" in the menu.

Kudos also for adding `install/updatesDB.md`, I guess with this file we do not need to do new `initDB` after updating to a new version.

Very nice, we may switch to Pakiti3 soon then.
