### ISSUE TITLE
Cross-Site Scripting (XSS)

### ISSUE THREAD

**Issue by joanmartinezcsuc** [CESNET/pakiti-server#147]
Hi, 
Recently I installed a new instance of pakiti-server and I found a XSS bug. The impact of this bug is low but I thought you would know it to correct it.

The url is the following:

https://XXXXXXXX.com/protected/cve.php?cveName=%3Cscript%3Ealert(%22xss%22);%3C/script%3E

Thanks!

**Comment by kouril** [comment]
Thanks for spotting the issue and reporting it. I've committed changes that sanitize user parameters correctly.

Daniel

**Comment by joanmartinezcsuc** [comment]
Thanks :)

**Comment by kouril** [comment]
All other values provided by the client (namely the contents of the report sent by the client) are escaped when they're being stored in the database. There shouldn't be other places to inject XSS strings, I close the ticket now.
