### ISSUE TITLE
Ubuntu CVEs are not being checked

### ISSUE THREAD

**Issue by mgrosa** [CESNET/pakiti-server#170]
Hi,
I am trying to use this tool to monitor the patching status of our Linux systems but we are having huge problems regarding Ubuntu systems.

The first problem is related with [Ubuntu](https://people.canonical.com/~ubuntu-security/oval/) itself: they decided to start compressing their OVAL files instead of letting us download uncompressed ones...
To handle this new situation I am using a script which wgets the compressed XML files and then decompresses them to the public location of my Pakiti server.
**EDIT:** A better solution was proposed by @lucasnetau on his pull request #169.

Now, my Pakiti server has the uncompressed XML files but I am thinking that it is not processing them as it is supposed to because it doesn't update the "Last Check" status, contrary to what happens with Debian and CentOS, and it doesn't show any CVE on a clearly vulnerable server.
![image](https://user-images.githubusercontent.com/47603363/80479059-5c735600-8946-11ea-95ba-2a4a5205b6eb.png)
![image](https://user-images.githubusercontent.com/47603363/80479189-8dec2180-8946-11ea-9076-546eea2aeb7a.png)

I have been searching for what may be the reason for this problems and I have found that it may be related with ["an uncontrolled change in the Canonical OVAL structure"](https://github.com/wazuh/wazuh/issues/3521#issuecomment-501635042).

Does anyone have any solution to this problem?

Thanks,
Miguel Rosa

**Comment by aleita** [comment]
any news on this issue. I have the same problem here.

<img width="1079" alt="Screenshot 2021-06-04 at 14 28 20" src="https://user-images.githubusercontent.com/6066940/120801171-1de49d80-c541-11eb-8885-0cb2c833886e.png">
