### ISSUE TITLE
Install fails - RedHat OVAL v1 deprecated

### ISSUE THREAD

**Issue by benjamindonnachie** [CESNET/pakiti-server#193]
Last year RedHat switched off v1 of their OVAL (See https://access.redhat.com/OVAL_v1_deprecation_announcement).  As a result, I'm unable to set up a new pakiti install as downloads of the vuln definitions fail.

Are there plans to update Pakiti to OVAL v2?

(I'll update with screenshots / error messages shortly)

**Comment by benjamindonnachie** [comment]
RedHat OVAL feed is now under https://access.redhat.com/security/data/oval/v2/

**Comment by HavrilaJ** [comment]
Hi, I updated links in install script, as we use it.

**Comment by benjamindonnachie** [comment]
Thanks!
